---

- name: Setup Logging
  hosts: servers
  become: yes
  vars:
    audit_passwd: true
    audit_shadow: true
    audit_sudo: true

  tasks:
  
  - name: Install Rsyslog
    apt:
      name: rsyslog
      state: latest
      update_cache: yes

  - name: Start Rsyslog Service
    service:
      name: rsyslog
      state: started
      enabled: yes

  - name: Enable Persistent Logs
    lineinfile:
      path: /etc/systemd/journald.conf
      regexp: "^#?Storage="
      line: "Storage=persistent"
    notify: Restart_Journald

  - name: Install auditd
    apt:
      name: auditd
      state: latest

  - name: Start Auditd Service
    service:
      name: auditd
      state: started
      enabled: yes

  - name: Deploy audit rules
    template:
      src: audit.rules.j2
      dest: /etc/audit/rules.d/audit.rules
      owner: root
      group: root
      mode: "0640"
    notify: Restart_Auditd

  - name: Load Audit Rules into kernel
    command: augenrules --load
    notify: Restart_Auditd

  handlers:
    - name: Restart_Journald
      service:
        name: systemd-journald
        state: restarted
    - name: Restart_Auditd
      service:
        name: auditd
        state: restarted
